services:
  db:
    image: postgres:17-alpine
    container_name: db-ssia
    restart: always
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: ssia
      POSTGRES_PASSWORD: ssia
    ports:
      - "5432:5432"
    volumes:
      - db-ssia:/var/lib/postgresql/data

volumes:
  db-ssia:
